--- 
apiVersion: tekton.dev/vlalphal
kind: PipelineResource
metadata:
  name: quote-frontend-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/camicodina/quote-frontend
---
apiVersion: tekton.dev/vlalphal
kind: PipelineResource
metadata:
  name: quote-frontend-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/demo-quote-backend/quote-frontend:tkn